export enum tagTypes {
  admin = "admin",
  schedule = "schedule",
  user = "user",
  area = "area",
  category = "category",
  tutorRequests = "tutorRequests",
  districts = "districts",
  auth = "auth",
  TutorHub = "TutorHub",
  testimonial = "testimonial",
  VideoTestimonial = "VideoTestimonial",
  FeatureMedia = "FeatureMedia",
  phoneVerify = "phoneVerify",
  upgradePackages = "upgradePackages",
  notice = "notice",
}

export const tagTypesList = [
  tagTypes.admin,
  tagTypes.schedule,
  tagTypes.user,
  tagTypes.area,
  tagTypes.category,
  tagTypes.tutorRequests,
  tagTypes.districts,
  tagTypes.auth,
  tagTypes.TutorHub,
  tagTypes.testimonial,
  tagTypes.VideoTestimonial,
  tagTypes.FeatureMedia,
  tagTypes.phoneVerify,
  tagTypes.upgradePackages,
  tagTypes.notice,
];
