export enum tagTypes {
  admin = "admin",
  Document = "Document",
  Note = "Note",
  schedule = "schedule",
  user = "user",
  area = "area",
  category = "category",
  tutorRequests = "tutorRequests",
  districts = "districts",
  auth = "auth",
  TutorHub = "TutorHub",
  testimonial = "testimonial",
  VideoTestimonial = "VideoTestimonial",
  FeatureMedia = "FeatureMedia",
  phoneVerify = "phoneVerify",
  upgradePackages = "upgradePackages",
  notice = "notice",
  application = "application",
  notification = "notification",
  review = "review",
  transaction = "transaction",
  applyForTutor = "applyForTutor",
  payment = "payment",
}

export const tagTypesList = [
  tagTypes.admin,
  tagTypes.application,
  tagTypes.schedule,
  tagTypes.user,
  tagTypes.area,
  tagTypes.category,
  tagTypes.tutorRequests,
  tagTypes.districts,
  tagTypes.auth,
  tagTypes.TutorHub,
  tagTypes.testimonial,
  tagTypes.VideoTestimonial,
  tagTypes.FeatureMedia,
  tagTypes.phoneVerify,
  tagTypes.upgradePackages,
  tagTypes.notice,
  tagTypes.Note,
  tagTypes.Document,
  tagTypes.notification,
  tagTypes.review,
  tagTypes.transaction,
  tagTypes.applyForTutor,
  tagTypes.payment,
];
